apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamcity-demo
  template:
    metadata:
      labels:
        app: teamcity-demo
    spec:
      containers:
      - name: teamcity-demo
        image: 10.0.60.124:5000/teamcity-demo:v1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
