apiVersion: v1
kind: Service
metadata:
  name: teamcity-demo
spec:
  type: NodePort
  selector:
    app: teamcity-demo
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
